import pip
pip.main(["install", "gspread"])
pip.main(["install", "df2gspread"])
pip.main(["install", "gspread_dataframe"])
pip.main(["install", "gspread-formatting"])
pip.main(["install", "requests"])
pip.main(["install", "selenium"])
pip.main(["install", "pandas"])
pip.main(["install", "lxml"])
pip.main(["install", "BeautifulSoup"])
pip.main(["install", "schedule"])
pip.main(["install", "regex"])
# pip.main(["install", ""])
print('install success!!!')